### PR TITLE
Improve the test of communication API and check both cases (UUID, CODE)

### PR DESCRIPTION
**Pull request by toch**
In a previous PR #136, we added the capacity to refer with CODE id rather than UUID. A fixture was added to test this new case. However, as there is a 1-1 relation between Claim and Feedback, we couldn't test both fixtures, as a Feedback would have been already linked to the Claim object used in the test.

We delete the created Feedback and it does the job.

### CODE REVIEW

**Comment by toch** [comment]
there is an issue now with the db test creation:

```
database "test_IMIS" already exists
```

**Comment by toch** [comment]
I think it's due to this commit b744f94277e83f999cdd417704e3345f31727315 removing ` --keep` as it is created just before with the sql script.

**Comment by toch** [comment]
Here what I tried:

* put back the `--keepdb` option
* remove the initialization script

none worked.

when I looked at other repo having tests with PostgreSQL, they are still using the `--keep` or `--keepdb` options:

* [core](https://github.com/openimis/openimis-be-core_py/blob/c543d1b40bc024ed746dc6df18ea1391e4b8ab28/.github/workflows/openmis-module-test-psql.yml#L6)
* [individual](https://github.com/openimis/openimis-be-individual_py/blob/4dc6281a0410e41fef6090626618925148523f45/.github/workflows/openmis-module-test-psql.yml#L10)
* [task management](https://github.com/openimis/openimis-be-tasks_management_py/blob/305465650333905e28ff4bf7cfdb9c853f893c05/.github/workflows/openmis-module-test-psql.yml#L67)

I've just tried again without the `keepdb` options without success. But this time, I get another error. Previously, the test failed as it complained that the tables did already exist. Now it fails because it does not find the `individual` module.

**Comment by tdethier** [comment]
@delcroip The error Christophe is describing (`ModuleNotFoundError: No module named 'individual'`) means that CORE-MIS features are now part of this module and that the CORE-MIS modules are not installed on the CI. Could you please check why this situation happened?

**Comment by delcroip** [comment]
We had to put some  coreMIS module on develop because they are part of the release (therefore they should not break the app) but I was told not to put the individual .... I fixed that in the meantime

**Comment by toch** [comment]
> We had to put some coreMIS module on develop because they are part of the release (therefore they should not break the app) but I was told not to put the individual .... I fixed that in the meantime

Thanks @delcroip 

I've checked what to do then with the present PR, it seems that it's not that relevant anymore considering the recent changes merged in develop (except the extra indentation starting line 241 in `test_api_communication.py`). Am I correct?

It seems the GitHub Actions to run the tests have been removed, so the test problem, is that correct too?

**Comment by delcroip** [comment]
> > We had to put some coreMIS module on develop because they are part of the release (therefore they should not break the app) but I was told not to put the individual .... I fixed that in the meantime
> 
> Thanks @delcroip
> 
> I've checked what to do then with the present PR, it seems that it's not that relevant anymore considering the recent changes merged in develop (except the extra indentation starting line 237 in `test_api_communication.py`). Am I correct?
> 
> It seems the GitHub Actions to run the tests have been removed, so the test problem, is that correct too?

we did not remove the CI but we are now using a CI define on the assembly (easier to managed and more coherent accross modules)

for the indentation l237, I trust you, I only hunted all error not all failures

**Pull request merged**
